import type { Metadata } from "next";
import { Zen_Maru_Gothic, Sora } from "next/font/google";
import { Provider } from "@itsatoshi/components/ui/provider"
import "./globals.css";

const zenMaruGothic = Zen_Maru_Gothic({
  variable: "--font-zen-maru-gothic",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${zenMaruGothic.variable} ${sora.variable}`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
